name: Kubernetes Bundle - Docker Dockerfile

on:
  push:
    branches: [main-1.32]
  pull_request:
    branches: [main-1.32]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/kubernetes-bundle-docker-dockerfile.yaml@1.1.45
    permissions:
      contents: write
      packages: write
      checks: write
